cdadocumentviewer-webgui/src/main/java/dk/kvalitetsit/cdadocumentviewer/dto/DocumentEntryTO.java
package dk.kvalitetsit.cdadocumentviewer.dto;

import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import org.openehealth.ipf.commons.ihe.xds.core.metadata.AvailabilityStatus;
import org.openehealth.ipf.commons.ihe.xds.core.metadata.DocumentEntry;

public class DocumentEntryTO {
	
	private static DateTimeFormatter dateTimeFormat = DateTimeFormat.forPattern("dd/MM/YYYY HH:mm");

	private DocumentEntry de;
	private boolean allowUpdate;
	private boolean allowDeprecate;
	private String documentEntryJsonFormatBase64Encoded;
	private String backendCode;
	
	public DocumentEntryTO(DocumentEntry de, boolean itiAllowUpdate, boolean itiAllowDeprecate, String documentEntryJsonFormatBase64Encoded, String backendCode) {
		this.de = de;
		if ((itiAllowUpdate) &&
			(de.getAvailabilityStatus().equals(AvailabilityStatus.APPROVED))) {
			this.allowUpdate = true;
		} else {
			this.allowUpdate = false;
		}

		if ((itiAllowDeprecate) &&
			(de.getAvailabilityStatus().equals(AvailabilityStatus.APPROVED))) {
			this.allowDeprecate = true;
		} else {
			this.allowDeprecate = false;
		}
		this.documentEntryJsonFormatBase64Encoded = documentEntryJsonFormatBase64Encoded;
		this.backendCode = backendCode;

	}
	
	public String getUniqueId() {
		return de.getUniqueId();
	}
	
	public String getEntryUuid() {
		return de.getEntryUuid();
	}
	
	public String getRepositoryUniqueId() {
		return de.getRepositoryUniqueId();
	}
	
	public String getDocumentType() {
		return (de.getTypeCode() != null ? (de.getTypeCode().getDisplayName() != null ? de.getTypeCode().getDisplayName().getValue() : "") : "");
	}
	
	public String getServiceStartTime() {
		if (de != null && de.getServiceStartTime() != null) {
			return dateTimeFormat.print(de.getServiceStartTime());
		} else {
			return "";
		}
	}
	
	public String getServiceStopTime() {
		if (de != null && de.getServiceStopTime() != null) {
			return dateTimeFormat.print(de.getServiceStopTime());
		} else {
			return "";
		}		
	}
	
	public String getStartSort() {		
	if (de != null && de.getServiceStartTime() != null) {
		return ""+de.getServiceStartTime().getMillis();	
	} else {
		return "0";
	}	
	}
	
	public String getStopSort() {
		if (de != null && de.getServiceStopTime() != null) {
			return ""+de.getServiceStopTime().getMillis();	
		} else {
			return "0";
		}		
	}
	
	public String getPatientId() {
		return de.getPatientId().getId();	
	}
	
	public String getHomeCommunityId() {
		return de.getHomeCommunityId();
	}

	public boolean isAllowUpdate() {
		return allowUpdate;
	}

	public boolean isAllowDeprecate() {
		return allowDeprecate;
	}
	
	public String getDocumentEntryJsonFormatBase64Encoded() {
		return documentEntryJsonFormatBase64Encoded;
	}

	public String getBackendCode() {
		return backendCode;
	}
	
}

cdadocumentviewer-webgui/src/main/java/dk/kvalitetsit/cdadocumentviewer/dto/DocumentMetadata.java
package dk.kvalitetsit.cdadocumentviewer.dto;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;

import com.fasterxml.jackson.annotation.JsonFormat;

public class DocumentMetadata extends CdaMetadata {

	public Code patientId;

	@JsonFormat(pattern="yyyy-MM-dd'T'HH:mm:ssZ")
	public Date reportTime;
	
	public Code organisation;
	
	public Person authorPerson;

	public Code typeCode;
	
	public List<Code> eventCodes;
	
	public String languageCode;
	
	public String title;
	
//	public Code contentTypeCode;
	
	
	private Code confidentialityCode;
	
	public Person legalAuthenticator;
	
	@JsonFormat(pattern="yyyy-MM-dd'T'HH:mm:ssZ")
	public Date serviceStartTime;
	
	@JsonFormat(pattern="yyyy-MM-dd'T'HH:mm:ssZ")
	public Date serviceStopTime;
	
	public Code sourcePatientId;
	
	public Person sourcePatientInfoPerson;
	public String sourcePatientInfoGender;
	@JsonFormat(pattern="yyyy-MM-dd'T'HH:mm:ssZ")
	public Date sourcePatientInfoDateOfBirth;
	
	public String uniqueId;
	
	public Code getPatientId() {
		return patientId;
	}

	public void setPatientId(Code patientId) {
		this.patientId = patientId;
	}

	public Date getReportTime() {
		return reportTime;
	}
	public String getReportTimeStringUTC() {
		if (this.reportTime != null) {
			return dateToStringTimeZone(this.reportTime, "UTC");
		}
		return null;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	public Code getOrganisation() {
		return organisation;
	}

	public void setOrganisation(Code organisation) {
		this.organisation = organisation;
	}

	public Person getAuthorPerson() {
		return authorPerson;
	}

	public void setAuthorPerson(Person authorPerson) {
		this.authorPerson = authorPerson;
	}

	public List<Code> getEventCodes() {
		return eventCodes;
	}

	public void setEventCodes(List<Code> eventCodes) {
		this.eventCodes = eventCodes;
	}

	public String getLanguageCode() {
		return languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Code getTypeCode() {
		return typeCode;
	}

	public void setTypeCode(Code typeCode) {
		this.typeCode = typeCode;
	}

//	public Code getContentTypeCode() {
//		return contentTypeCode;
//	}
//
//	public void setContentTypeCode(Code contentTypeCode) {
//		this.contentTypeCode = contentTypeCode;
//	}

	public Code getConfidentialityCode() {
		return confidentialityCode;
	}

	public void setConfidentialityCode(Code confidentialityCode) {
		this.confidentialityCode = confidentialityCode;
	}

	public Person getLegalAuthenticator() {
		return legalAuthenticator;
	}

	public void setLegalAuthenticator(Person legalAuthenticator) {
		this.legalAuthenticator = legalAuthenticator;
	}

	public Date getServiceStartTime() {
		return serviceStartTime;
	}
	public String getServiceStartTimeStringUTC() {
		if (this.serviceStartTime != null) {
			return dateToStringTimeZone(this.serviceStartTime, "UTC");
		}
		return null;
	}

	public void setServiceStartTime(Date serviceStartTime) {
		this.serviceStartTime = serviceStartTime;
	}

	public Date getServiceStopTime() {
		return serviceStopTime;
	}
	public String getServiceStopTimeStringUTC() {
		if (this.serviceStopTime != null) {
			return dateToStringTimeZone(this.serviceStopTime, "UTC");
		}
		return null;
	}

	public void setServiceStopTime(Date serviceStopTime) {
		this.serviceStopTime = serviceStopTime;
	}

	public Code getSourcePatientId() {
		return sourcePatientId;
	}

	public void setSourcePatientId(Code sourcePatientId) {
		this.sourcePatientId = sourcePatientId;
	}

	public Person getSourcePatientInfoPerson() {
		return sourcePatientInfoPerson;
	}

	public void setSourcePatientInfoPerson(Person sourcePatientInfoPerson) {
		this.sourcePatientInfoPerson = sourcePatientInfoPerson;
	}

	public String getSourcePatientInfoGender() {
		return sourcePatientInfoGender;
	}

	public void setSourcePatientInfoGender(String sourcePatientInfoGender) {
		this.sourcePatientInfoGender = sourcePatientInfoGender;
	}

	public Date getSourcePatientInfoDateOfBirth() {
		return sourcePatientInfoDateOfBirth;
	}

	public void setSourcePatientInfoDateOfBirth(Date sourcePatientInfoDateOfBirth) {
		this.sourcePatientInfoDateOfBirth = sourcePatientInfoDateOfBirth;
	}
	public String getSourcePatientInfoDateOfBirthString() {
		return dateToStringTimeZone(this.sourcePatientInfoDateOfBirth, null).substring(0,  8);
	}

	public String getUniqueId() {
		return uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}
	
	private String dateToStringTimeZone(Date date, String timeZone) {
		DateFormat formatter = new SimpleDateFormat("yyyyMMddHHmmss");
		if (timeZone != null) {
			formatter.setTimeZone(TimeZone.getTimeZone(timeZone));	
		}
		return formatter.format(date);
	}

	@Override
	public String toString() {
		return super.toString() + ". DocumentMetadata [patientId=" + patientId + ", reportTime=" + reportTime + ", organisation="
				+ organisation + ", authorPerson=" + authorPerson + ", typeCode=" + typeCode + ", eventCodes="
				+ eventCodes + ", languageCode=" + languageCode + ", title=" + title  
				+ ", confidentialityCode=" + confidentialityCode + ", legalAuthenticator="
				+ legalAuthenticator + ", serviceStartTime=" + serviceStartTime + ", serviceStopTime=" + serviceStopTime
				+ ", sourcePatientId=" + sourcePatientId + ", sourcePatientInfoPerson=" + sourcePatientInfoPerson
				+ ", sourcePatientInfoGender=" + sourcePatientInfoGender + ", sourcePatientInfoDateOfBirth="
				+ sourcePatientInfoDateOfBirth + ", uniqueId=" + uniqueId + "]";
	}


}

cdadocumentviewer-webgui/src/main/java/dk/kvalitetsit/cdadocumentviewer/gui/UploadController.java
package dk.kvalitetsit.cdadocumentviewer.gui;

import java.util.Arrays;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;

import dk.kvalitetsit.cdadocumentviewer.dto.DocumentMetadata;
import dk.kvalitetsit.cdadocumentviewer.dto.LoggableResult;
import dk.kvalitetsit.cdadocumentviewer.dto.MetadataInput;
import dk.kvalitetsit.cdadocumentviewer.dto.UploadFileRequest;
import dk.kvalitetsit.cdadocumentviewer.dto.UploadFileSession;
import dk.kvalitetsit.cdadocumentviewer.dto.UploadResponseInfo;
import dk.kvalitetsit.cdadocumentviewer.service.ErrorConverterUtil;
import dk.kvalitetsit.cdadocumentviewer.service.ReferenceDataService;
import dk.kvalitetsit.cdadocumentviewer.service.RepositoryProfileIti41Service;
import dk.kvalitetsit.cdadocumentviewer.service.UploadService;

@Controller
@SessionAttributes({"rememberedFileContent", "uploadFileSession"})
public class UploadController {

	private static Logger LOGGER = LoggerFactory.getLogger(UploadController.class);

	@Autowired
	UploadService uploadService;
	
	@Autowired
	RepositoryProfileIti41Service repositoryProfileIti41Service;
	
	@Autowired
	ReferenceDataService referenceDataService;
	
	@ModelAttribute("uploadFileSession")
	private  UploadFileSession uploadFileSession() {
	    return new UploadFileSession();
	}

	@RequestMapping("/upload")
	public String upload(Model model,
			@ModelAttribute("externalDocumentId") String externalDocumentId, 
			@ModelAttribute("entryUuid") String entryUuid,
			@ModelAttribute("repositoryId") String repositoryId, 
			@ModelAttribute("uploadFileSession") UploadFileSession uploadFileSession) {
		//Purpose: The user select document to upload and repository (repository is given if its an update)  
		
		List<String> errorList = uploadService.prepareUpload(externalDocumentId, entryUuid, repositoryId, uploadFileSession);
		if (errorList.size() > 0) {
			model.addAttribute("errorList", errorList);
			return returnUpload(model, uploadFileSession);
		}
		
		if (uploadFileSession.isReplaceOperationActive()) {
			model.addAttribute("selectedRepositoryName", uploadFileSession.getReplaceRepository().getName());
			model.addAttribute("uploadOperation",  "Ret af " + uploadFileSession.getReplaceExternalDocumentId());
		} else {
			model.addAttribute("repositoryList", repositoryProfileIti41Service.getRepositoryAsDropDownListForUpload().getDropDownListValues());
			model.addAttribute("uploadOperation",  "Opret");
		}
		
		model.addAttribute("request",  new UploadFileRequest());
		return "upload";  
	}
	
	@RequestMapping(value = "/showUpload", method = RequestMethod.POST)
	public String showUpload(Model model, @ModelAttribute("uploadRequest") UploadFileRequest request,
			@ModelAttribute("uploadFileSession") UploadFileSession uploadFileSession) {
		//Purpose: The user can look at the metadata and document. And can select optional metadata
		try {
			
			List<String> errorList = uploadService.validateShowUpload(request, uploadFileSession);
			if (errorList.size() > 0) {
				model.addAttribute("errorList", errorList);
				return returnUpload(model, uploadFileSession);
			}
			
			DocumentMetadata documentMetadata = uploadService.getMetaDataFromUploadFile(request);
			byte[] fileContent = uploadService.getBytesFromUploadFile(request);
			
			addTooltipToModel(model);

			model.addAttribute("metadataInput",  new MetadataInput());
			model.addAttribute("selectedNA", "N/A");
			model.addAttribute("valueRepository", uploadFileSession.getRepository().getName());
			model.addAttribute("valueHomecommunityid", uploadFileSession.getRepository().getHomeCommunityId());

			//add all dropwdownlist with values
			model.addAttribute("availabilityStatusList", referenceDataService.getAvailabilityStatusList());
			model.addAttribute("healthcareFacilityTypeCodeList", referenceDataService.getHealthcareFacilityTypeCodeList(null));
			model.addAttribute("objectTypeList", referenceDataService.getObjectTypeList());
			model.addAttribute("practiceSettingCodeList", referenceDataService.getPracticeSettingCodeList(null));
			if (documentMetadata.getFormatCode() == null) { //if not included, allow the user to select one
				model.addAttribute("formatCodeList", referenceDataService.getFormatCodeList(null));
			}

			if (uploadFileSession.isReplaceOperationActive()) {
				model.addAttribute("uploadOperation",  "Ret af " + uploadFileSession.getReplaceExternalDocumentId());
			} else {
				model.addAttribute("uploadOperation",  "Opret");
			}
			model.addAttribute("fileContent", new String(fileContent));
			model.addAttribute("fileMetadata", documentMetadata);
			model.addAttribute("rememberedFileContent", new String(fileContent));

		} catch (Exception e) {
			LOGGER.error("Template upload failed",e);
			List<String> errorList = Arrays.asList("Fejl ved håndtering af dokument eller dets metadata");
			model.addAttribute("errorList", errorList);
			return returnUpload(model, uploadFileSession);
		}

		return "showUploadContent";   	
	}
	
	private String returnUpload(Model model, UploadFileSession uploadFileSession) {
		if (uploadFileSession.isReplaceOperationActive()) {
			return upload(model, uploadFileSession.getReplaceExternalDocumentId(), uploadFileSession.getReplaceEntryUuid(), 
					uploadFileSession.getReplaceRepository().getRepositoryuniqueid(), uploadFileSession);
		} else {
			return upload(model, null, null, null, uploadFileSession );
		}
	}
	

	@RequestMapping(value = "/uploadDocument", method = RequestMethod.POST)
	public String uploadDocument(Model model, @ModelAttribute("metadataInput") MetadataInput request, 
			@ModelAttribute("rememberedFileContent") String fileContent, 
			@ModelAttribute("uploadFileSession") UploadFileSession uploadFileSession) {
		//Purpose: The document is uploaded
		
		try {
			LoggableResult<UploadResponseInfo> result = uploadService.doUpload(fileContent, request, uploadFileSession);
			if (result != null) {
				UploadResponseInfo uploadResponseInfo = result.getResult();
				if (uploadResponseInfo.allOk()) {
					model.addAttribute("notification", "Dokument uploadet (" + uploadResponseInfo.getExternalDocumentId() + ")");
					model.addAttribute("uploadResponseInfo", uploadResponseInfo);
					if (!uploadResponseInfo.getErrorList().isEmpty()) {
						model.addAttribute("errorList", ErrorConverterUtil.addFirstError(uploadResponseInfo.getErrorList(), "Advarsler ved upload af dokument. Advarslerne er:"));
					}
				} else {
					model.addAttribute("errorList", ErrorConverterUtil.addFirstError(uploadResponseInfo.getErrorList(), "Fejl ved upload af dokument. Fejlene er:"));
				}
				addRequestResponseModel(model, result.getRequestId(), result.getResponseId());
			}

		} catch (Exception e) {
			LOGGER.error("Template upload failed",e);
			model.addAttribute("errorList", ErrorConverterUtil.addFirstError(Arrays.asList(e.getMessage()), "Fejl ved upload af dokument. Fejlen er:"));
		}

		return "showUploadResult";   	
	}
	
	private void addTooltipToModel(Model model) {
		String tooltipPrefix = "Der søges på kodeværdien indenfor codeScheme: ";
		model.addAttribute("tooltipClassCode", tooltipPrefix+referenceDataService.getClassCodeScheme());
		model.addAttribute("tooltipFormatCode", tooltipPrefix+referenceDataService.getFormatCodeScheme());
		model.addAttribute("tooltipHealthcareFacilityTypeCode", tooltipPrefix+referenceDataService.getHealthcareFacilityTypeCodeScheme());
		model.addAttribute("tooltipPracticeSettingCode", tooltipPrefix+referenceDataService.getPracticeSettingCodeScheme());
	}
	
	private void addRequestResponseModel(Model model, String requestId, String responseId) {
		model.addAttribute("requestId", requestId);
		model.addAttribute("responseId", responseId);
	}

}

cdadocumentviewer-webgui/src/main/webapp/WEB-INF/jsp/about.jsp
<%@taglib prefix="c"   uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>

<jsp:include page="header.jsp" />

<div class="container">

<div class="panel panel-default">
	<div class="panel-heading">Om CDA Document Viewer</div>
	<div class="panel-body">

<table class="table table-bordered">
  <tbody>
    <tr>
      <td>STS url</td>
      <td><c:out value="${stsendpoint}" /></td>
    </tr>
  </tbody>
</table>

<table class="table table-bordered">
  <tbody>
    <tr>
      <td>Backends</td>
      <td>
            <c:if test="${backendList != null}">
            <table class="table">
                <tbody>
                    <c:forEach var="iti18Elm" items="${backendList}">
                    <table class="table table-bordered">
                        <tbody>
                            <tr><td>Backend</td><td>${iti18Elm.name}</td></tr>
                            <tr><td>Kode</td><td>${iti18Elm.backendCode}</td></tr>
                            <tr><td>ITI-18 url</td><td>${iti18Elm.endpoint}, dgws=${iti18Elm.dgws}</td></tr>
                            <tr><td>ITI-43 url</td><td>${iti18Elm.endpointIti43}, dgws=${iti18Elm.dgwsIti43}</td></tr>
                        </tbody>
                    </table>
                   </c:forEach>
                </tbody>
            </table>
        </c:if>
      </td>
    </tr>
  </tbody>
</table>

<table class="table table-bordered">
  <tbody>
    <tr>
      <td>Repositories</td>
      <td>
      		<c:if test="${repoList != null}">
			<table class="table">
				<tbody>
					<c:forEach var="iti41Elm" items="${repoList}">
                    <table class="table table-bordered">
                        <tbody>
                            <tr><td>Repository</td><td>${iti41Elm.name}</td></tr>
                            <tr><td>RepositoryUniqueId</td><td>${iti41Elm.repositoryuniqueid}</td></tr>
                            <tr><td>HomeCommunityId</td><td>${iti41Elm.homeCommunityId}</td></tr>
                            <tr><td>ITI-41 url</td><td>${iti41Elm.endpoint}, dgws=${iti41Elm.dgws}, uploadAllowed=${iti41Elm.uploadallowed}, updateAllowed=${iti41Elm.updateallowed}</td></tr>
                            <tr><td>ITI-57 url</td><td>${iti41Elm.endpointIti57}, dgws=${iti41Elm.dgwsIti57}, deprecateAllowed=${iti41Elm.deprecateallowed}</td></tr>
                            <tr><td>Backend kode</td><td>${iti41Elm.backendCode}</td></tr>
                            <tr><td>DokumentTyper</td><td>${iti41Elm.validDocTypes}</td></tr>
                        </tbody>
                    </table>
					</c:forEach>
				</tbody>
			</table>
		</c:if>
      </td>
    </tr>
  </tbody>
</table>



</div>
</div>
</div>


<jsp:include page="footer.jsp" />

cdadocumentviewer-webgui/src/main/webapp/WEB-INF/jsp/footer.jsp
</div>
</body>
</html>

cdadocumentviewer-webgui/src/main/webapp/WEB-INF/jsp/header.jsp
<%@taglib prefix="c"   uri="http://java.sun.com/jsp/jstl/core" %>
<%@page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>CDA Document Viewer</title>
 	<link type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<link type="text/css" href="css/dataTables.bootstrap.min.css" rel="stylesheet">
	<link type="text/css" href="css/jquery-ui.css" rel="stylesheet">
 	<script type="text/javascript" src="js/jquery.min.js" ></script>
 	<script type="text/javascript" src="js/jquery.dataTables.min.js" ></script>
 	<script type="text/javascript" src="js/dataTables.bootstrap.min.js" ></script>
 	<script type="text/javascript" src="js/jquery-ui.js" ></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand">CDA Document Viewer</div>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="newsearch">Søg</a></li>
      <li><a href="upload">Upload</a></li>
      <li><a href="about">Om...</a></li>
    </ul>
  </div>
</nav>
	

cdadocumentviewer-webgui/src/main/webapp/WEB-INF/jsp/showDeprecateResult.jsp
<%@taglib prefix="c"   uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>

<jsp:include page="header.jsp" />

<div class="container">
	<c:set var="deprecateResult" value="${deprecateResult}" />

	<c:if test="${notification != null}">
		<div class="alert alert-success" role="alert">
			<c:out value="${notification}" />
		</div>
	</c:if>
	<c:if test="${deprecateErrors != null}">
		<div class="alert alert-warning" role="alert">
			<c:forEach var="error" items="${deprecateErrors}">
					<p>
						<c:out value="${error}" />
					</p>
			</c:forEach>
		</div>
	</c:if>
	<button onclick="window.history.back();" class="btn btn-primary">Tilbage til søgning</button>
	<div>
		<br/>
		<a href="getLogEntry?logEntryId=<c:out value="${requestId}"/>">Download request (Deprecate)</a> <a href="getLogEntry?logEntryId=<c:out value="${responseId}"/>">Download response (Deprecate)</a>
	</div>
</div>

<jsp:include page="footer.jsp" />

cdadocumentviewer-webgui/src/main/webapp/WEB-INF/jsp/showUploadResult.jsp
<%@taglib prefix="c"   uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>

<jsp:include page="header.jsp" />

<c:set var="uploadResult" value="${uploadResult}" />

<div class="container">
	<c:if test="${notification != null}">
		<div class="alert alert-success" role="alert">
			<c:out value="${notification}" />
		</div>
		<c:url value="/search" var="url">
			<c:param name="patientID" value="${uploadResponseInfo.patientId}" />
			<c:param name="uniqueID" value="${uploadResponseInfo.externalDocumentId}" />
			<c:param name="backendCode" value="${uploadResponseInfo.backendCodeToSearchDocument}" />
			<c:param name="status" value="Approved" />
			<c:param name="typeStable" value="true" />
		</c:url>
		<a href="${url}">
  				<button class="btn btn-primary">Fremsøg</button>
		</a>
		<p>&nbsp;</p> 
	</c:if>
	
	<c:if test="${errorList != null}">
		<div class="alert alert-warning" role="alert">
		<c:forEach var="errorElm" items="${errorList}">
				<p>
					<c:out value="${errorElm}" />
				</p>
		</c:forEach>
		</div>
	</c:if>
	
	
	<div>
		<br/>
		<a href="getLogEntry?logEntryId=<c:out value="${requestId}"/>">Download request (Upload)</a> <a href="getLogEntry?logEntryId=<c:out value="${responseId}"/>">Download response (Upload)</a>
	</div>
	
</div>


<jsp:include page="footer.jsp" />

cdadocumentviewer-webgui/src/main/webapp/WEB-INF/jsp/upload.jsp
<%@taglib prefix="c"   uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>

<jsp:include page="header.jsp" />
<div class="container">
	<c:if test="${errorList != null}">
		<div class="alert alert-warning" role="alert">
			<c:forEach var="errorElm" items="${errorList}">
					<p>
						<c:out value="${errorElm}" />
					</p>
			</c:forEach>
		</div>
	</c:if>

	<div class="panel panel-default">
		<div class="panel-heading">Upload dokument (${uploadOperation})</div>
		<div class="panel-body">
			<form:form modelAttribute="request" action="showUpload" enctype="multipart/form-data" method="POST">
				
				<div class="form-group">
					<label for="file">Vælg fil</label>
					<input class="form-control" type="file" id="cdaFile" name="cdaFile" style="padding-bottom:40px">
				</div>
			<c:if test="${selectedRepositoryName == null}">
				<div class="form-group">
					<label for="repository">Vælg repository</label>
					<form:select class="form-control" path="repositoryEndpoint">
						<c:forEach var="repositorySelect" items="${repositoryList}">
								<form:option value="${repositorySelect.code}"><c:out value="${repositorySelect.name}" /></form:option>
						</c:forEach>
			 		</form:select>
				</div>
			</c:if>
			<c:if test="${selectedRepositoryName != null}">
				<div class="form-group">
					<label for="repository">Repository</label>
					<input type="text" class="form-control" id="repositoryName" name="repositoryName" readonly = "readonly" value="${selectedRepositoryName}"/>
				</div>
			
			</c:if>	
				<button type="submit" class="btn btn-primary">Preview Upload</button>
		
			</form:form>
		</div>
	</div>
</div>

<jsp:include page="footer.jsp" />